name: Monolith reuse

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Monolith
        uses: ./.github/actions/monolith
        with:
          command_install: 'yarn install --frozen-lockfile'
          version_manager: 'yarn'
